name:                flashairdd
version:             0.1.0.0
github:              "githubuser/flashairdd"
license:             BSD3
author:              "Haruka Nakajima"
maintainer:          "haru2036@gmail.com"
copyright:           "2018 Haruka Nakajima"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/flashairdd#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - http-client
  - text
  - bytestring
  - download
  - directory
  - regex-pcre
  - regex-posix
  - regex-base
  - split
  - aeson
  - system-fileio

executables:
  flashairdd-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flashairdd
    - scotty
    - transformers

tests:
  flashairdd-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flashairdd
